# See the documentation for more information:
# https://packit.dev/docs/configuration

specfile_path: fedora/cpr.spec

downstream_package_name: cpr
upstream_project_url: https://github.com/libcpr/cpr
issue_repository: https://github.com/libcpr/cpr

upstream_package_name: cpr

jobs:
  - job: propose_downstream
    trigger: release
    dist_git_branches:
      - fedora-all
      - epel-9
  - job: koji_build
    trigger: commit
    dist_git_branches:
      - fedora-all
      - epel-9
  - job: bodhi_update
    trigger: commit
    dist_git_branches:
      - fedora-latest # branched version, rawhide updates are created automatically
      - fedora-stable
      - epel-9
